### ISSUE TITLE
Support relative feed and post links when parsing feed XML

### ISSUE THREAD

**Issue by SebastianAigner** [msasikanth/twine#128]
Hi!

When I add my feed (https://sebi.io/feed.xml) on the iOS version of the app (installed from the App Store), it crashes with no further information 😅

**Comment by msasikanth** [comment]
Identified the cause for this crash, looks like the feed uses relative paths for links rather than providing full links. Since most of the RSS feeds provide full links, the app is optimised towards that, the only time I try to create a "safe" URL with the relative path is for images. 

One of the main problems with trying to create this safe URL is we need to have the correct host domain or else these URLs I created with the relative paths won't work. So far I have used the link that is present in the feeds `<link>` tag as the root because that's a safe assumption to make. But in the feed you have provided even that is relative, so it becomes harder to have a generalised solution for this.

I am aware the app should have shown an error, it's broken in the recent update because of a component change. I have it in my to-do to resolve it in the next update.

**Comment by msasikanth** [comment]
I usually use the [RSS validator](https://validator.w3.org/feed/) from w3 and it recommends the following approach for adding self URLs to the feeds to support vast majority of feed readers.

https://validator.w3.org/feed/docs/warning/RelativeSelf.html

**Comment by SebastianAigner** [comment]
The blog is a default Jekyll installation :)

**Comment by msasikanth** [comment]
> The blog is a default Jekyll installation :)

Yes, I understand. Other than showing an error when adding a feed, I cannot do much in terms of building relative URLs, it needs `xml:base` which adds a base URL or needs to contain absolute URLs in all links 😅

**Comment by msasikanth** [comment]
I will spend some time thinking about this issue, it would be great to handle relative links to provide the most optimal experience for users. Let me see what I can do 👀

**Comment by SebastianAigner** [comment]
Btw, you're right: There was a misconfiguration on my Jekyll site, it would seem.

**Comment by SebastianAigner** [comment]
Yup, app works fine now that [it's a valid Atom feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsebi.io%2Ffeed.xml). As long as the app doesn't crash when someone adds a wrong URL, I'd consider this fixed :) You can rightfully consider anything beyond that out of scope (not sure how many other pages are similarly misconfigured :D)

**Comment by msasikanth** [comment]
> Btw, you're right: There was a misconfiguration on my Jekyll site, it would seem.

Got it, the crash is resolved now. Then I will rename this issue and keep it open. I have a prototype for supporting relative URLs, I will explore that option later on.

**Comment by msasikanth** [comment]
> Yup, app works fine now that [it's a valid Atom feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsebi.io%2Ffeed.xml). As long as the app doesn't crash when someone adds a wrong URL, I'd consider this fixed :) You can rightfully consider anything beyond that out of scope (not sure how many other pages are similarly misconfigured :D)

Is it possible to link the configuration change you had to make? Would be useful to point to people in case someone else raises an issue with their feed 😅

**Comment by SebastianAigner** [comment]
Totally! https://github.com/SebastianAigner/SebastianAigner.github.io/commit/04972a11c511e357240e909de46e5ec3182558ba
