### ISSUE TITLE
cannot add atom feeds from Microsoft RSS feed picker

### ISSUE THREAD

**Issue by owocado** [msasikanth/twine#221]
**Describe the bug**
hello, thank you for making this useful app. In this issue, I am reporting the following bug report.

**To Reproduce**
1. Go to https://support.microsoft.com/en-us/rss-feed-picker
2. Pick any entry from Products drop-down
3. Copy the link of RSS feed shown
4. Try to add in Twine app and see error
5. It says "Provided link doesn't contain valid RSS/Atom feed" but if you open the rss link in browser, you can see the XML payload

**Screenshots**

**Device Information**
 - Device: Redmi 10 Pro
 - OS: Android 13
 - App Version: 1.31.0 (142)

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

**Comment by owocado** [comment]
hmm I searched for issues here and saw you mentioned W3's RSS feed validator so I tried that tool and looks like said Microsoft RSS feeds do not validate. could that be the reason? 👀

**Comment by msasikanth** [comment]
Hi, thanks for reporting the issue. There might be some incorrect tag present the RSS feed. Is the issue reproducible when using Atom feed as well? 

I will take a look at why the RSS feed parsing is failing.

**Comment by msasikanth** [comment]
It looks like the following feeds include BOM at start of the document/feed which is causing the parser to not properly move ahead with parsing.

**Comment by vanniktech** [comment]
I also maintain a RSS Reader and you won't believe how many things you have to take into consideration. I saw that you started implementing some like supporting multiple feed standards, multiple date formats etc. 

I'm stripping the bom away before parsing the Feed. If I remember correctly, I'm actually stripping anything away until the first `<` because there are also feeds that like to place strings before the actual xml tags ...

Another thing that I saw when you replaced your parsing with a multiplatform library is that you don't parse HTML. However HTML websites can actually reference their feeds (`<link rel="alternate" type="application/rss+xml" title="RSS" href="/rss.xml" />`) so it's nice when you for instance try to add a website, automatically parse the html get all of the feeds (there can be more) and then add them automatically in one go.

**Comment by owocado** [comment]
> Hi, thanks for reporting the issue. There might be some incorrect tag present the RSS feed. Is the issue reproducible when using Atom feed as well?
> 
> I will take a look at why the RSS feed parsing is failing.

hello, yes I have tried both atom & RSS feed links and same issue happens.

**Comment by msasikanth** [comment]
> Another thing that I saw when you replaced your parsing with a multiplatform library is that you don't parse HTML. However HTML websites can actually reference their feeds (<link rel="alternate" type="application/rss+xml" title="RSS" href="/rss.xml" />) so it's nice when you for instance try to add a website, automatically parse the html get all of the feeds (there can be more) and then add them automatically in one go.

Hi, I do parse HTML when trying to fetch a feed and find the link to the feed.

**Comment by msasikanth** [comment]
> I'm stripping the bom away before parsing the Feed. If I remember correctly, I'm actually stripping anything away until the first < because there are also feeds that like to place strings before the actual xml tags ...

@vanniktech how are you doing this? Are you using regex to strip the BOM or a different method? At the moment I am trying regex to strip it away and it is working. Just want to check if there is a alternative you have tried.

**Comment by vanniktech** [comment]
I'm operating on a `ByteArray` which I then convert to a String using the desired charset (this is important, many Russian feeds otherwise break), and `.removePrefix("\uFEFF") // Bom.` then I use `byteArrayString.indexOfAny` to find any of the desired starting tags such as `<?xml`, `<html` or from all the specifications that I use and drop the string. For now this seems to be handling all of the cases. As for the Russian Feed I think it was this one https://www.opennet.ru/opennews/opennews_review.rss which you can use to test that it works correctly and display the cyrillic alphabet.
