### ISSUE TITLE
Scroll position resets when navigating back

### ISSUE THREAD

**Issue by zupat** [msasikanth/twine#272]
**Describe the bug**
When scrolling through the feed, the scroll position will go back to the top when a new article is closed.

This might be related to #271 but I created another issue just in case the root cause differs.

**Screenshots**

https://github.com/msasikanth/twine/assets/30532952/359e3bb6-06f2-4cb0-9b9e-629a0fed57a0

**Device Information**
 - OS: Android 13
 - App Version 1.33.0

**Comment by FreedomChuks** [comment]
Can I raise a PR to fix this?

**Comment by msasikanth** [comment]
Yes, if you found the cause for the issue, feel free to do that.

**Comment by msasikanth** [comment]
Found the cause, this is happening because we are updating the post state when we open the reader view. This causes the home list which is paginated to refresh and causing it to change the scroll position. This happens when we mark a post as read as well from the home screen options.

This only happens when we scroll to a certain position, where it loads a new "page" from the paging list. After navigation, the scroll position resets now. But if we are still on the default/initial page, it doesn't change scroll position.
