### ISSUE TITLE
Cannot add "This Week in Gnome" Feed

### ISSUE THREAD

**Issue by Humorist2601** [msasikanth/twine#607]
**Describe the bug**
Whenever I try to add TWIG feed, it errors out and says "Provided Link Doesn't Containt Valid Atom/RSS Feed while in actuality it is a RSS 2.0 Feeed

**Device Information**
 - Device: Pixel 4a 5g
 - OS: Android 14
 - App Version 1.44.1

**Comment by rickdtc** [comment]
Happened to me to, check #587 and #589, it was fixed in a recent commit

You can get an apk from the latest Android pod build on actions, it's fixed, i.e the release.apk from [here](https://github.com/msasikanth/twine/actions/runs/9394511345), if you don't wanna go through that hassle just wait for the next release 

but however the feed is not sorted for me, the related issue should be #427

**Comment by msasikanth** [comment]
It's resolved in the newer version and a update is rolling out.
