### ISSUE TITLE
Pinned Feeds Bar

### ISSUE THREAD

**Issue by IndomitableAlbus** [msasikanth/twine#779]
Hi Dev.
The Apps great but the pined bar at the bottom is so unsightly, please offer a hide option.

Also the accent colour keeps changing, please give us a static Colour choice.

![20241025-182642](https://github.com/user-attachments/assets/db61f993-5a6b-41f1-ae58-5266285e7ba1)

**Comment by IndomitableAlbus** [comment]
"Closed this as not planed"

This was valid, constructive, criticism and an issue that may have contributed to bad Playstore reviews but if you can't be bothered, I'll go elseware.

**Comment by msasikanth** [comment]
iirc I have already addressed similar comment before in issues. While I am appreciative of constructive feedback, I didn't want to repeat the same response. 

But TLDR, the bottom bar and dynamic theming based on the featured item are design features of the app. We are planning to hide the bottom bar on scroll. 

We are also exploring newer designs to minimise the bottom bar (this I haven't shared in GH issues before), but we don't have any updates on it yet. 

Since this is a duplicate issue, I closed it as such.
